In [ ]:
import numpy as np

# Numpy 알아보기

1. 특정 자료형을 명시적으로 지정함 : dtype ='lnt'|np.int32
2. arr1 배열이 몇행 몇열? :: shape
3. shape :: 몇행 몇열 // size :: 원소의 갯수 

In [ ]:
arr1 = np.array([[1.0, 2, 3], [4,5,6]], dtype=np.int32)

# 함수 사용
print(arr1)
print(type(arr1))
print(np.ndim(arr1))
print(np.shape(arr1))
print(np.size(arr1))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2
(2, 3)
6


In [ ]:
# 필드 사용
print(arr1.ndim)
print(arr1.shape)
print(arr1.size)
print(arr1.dtype)

2
(2, 3)
6
int32


<함수와 필드를 똑같이 사용했지만 다른 한가지>

타입함수와 dtype 필드는 완전히 다른것임

dtype은 요소요소가 나오는 것이고,
타입 함수는 ndarray 로 나온다.



---



# .astype() 함수 :: 타입을 한번에 바꿔주는 함수

arr1 배열의 원소값 타입을 한번에 바꾸는 함수로 가장 많이 쓰이는 함수


In [ ]:
arr1_1=arr1.astype(np.float64)
print(arr1_1)

[[1. 2. 3.]
 [4. 5. 6.]]




---



# .reshape() 함수 :: 함수를 새로 정렬해주는 함수

In [ ]:
arr2 = np.arange(32).reshape(8,4)
print(arr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]




---



# 인덱싱과 슬라이싱

1. 인덱싱(콜론(:)을 사용하지 않음)
- 음수가 붙으면 뒤에서 n번째로 이해
- 뒤에 수가 없으면 끝까지 [1:]
- 하나만 콕 찝는 것

2. 슬라이싱(콜론(:)이 들어감)
- 여기~저기까지 훑는 거:: 범위:: 구간

In [ ]:
narray = np.arange(5)
narray

array([0, 1, 2, 3, 4])

In [ ]:
print(narray[1],narray[-1])
print(narray[1:])
print(narray[:])
print(narray[0:5]) # 이렇게는 잘 안쓰고 위 처럼 사용
print(narray[2:4])

1 4
[1 2 3 4]
[0 1 2 3 4]
[0 1 2 3 4]
[2 3]


In [ ]:
np.random.seed(0) # 랜덤하게 나오는 값이 전부 똑같이 나옴 (0으로 줬기 때문에.)
narray2 = np.random.randint(10,20,16).reshape(4,4)
print(narray2)
narray2

[[15 10 13 13]
 [17 19 13 15]
 [12 14 17 16]
 [18 18 11 16]]


array([[15, 10, 13, 13],
       [17, 19, 13, 15],
       [12, 14, 17, 16],
       [18, 18, 11, 16]])



---



# 문제 (1~4)

1. narray2 중에서 첫번째 줄의 13을 가져오려면? 인덱싱과 슬라이싱을 어떻게 쓸까?
- 슬라이싱은 사용하지 않음(인덱싱만 사용)

In [ ]:
print(narray2[0,2]) # [행, 렬]
print(narray2[0][2]) # [행][렬] 

13
13


2. narray2 중에서 두번째 줄을 가져오려면? 슬라이싱을 사용해야한다.

In [ ]:
print(narray2[1,0:4])
print(narray2[1,0:])
print(narray2[1,:])
print(narray2[1:2,:]) # 얘만 2차원으로 표현된다.
print(narray2[1][0:4])
print(narray2[1][0:])
print(narray2[1][:])
print(narray2[1:2][:]) # 얘만 2차원으로 표현된다.

[17 19 13 15]
[17 19 13 15]
[17 19 13 15]
[[17 19 13 15]]
[17 19 13 15]
[17 19 13 15]
[17 19 13 15]
[[17 19 13 15]]


3. 전체 행에 대해서, 4번째 열만 가져오려면?

In [ ]:
print(narray2[0:4, 3:4])
print(narray2[:, 3:])
print(narray2[0:4, 3])
print(narray2[:, 3])

[[13]
 [15]
 [16]
 [16]]
[[13]
 [15]
 [16]
 [16]]
[13 15 16 16]
[13 15 16 16]


4. 전체 행에 대해서 1, 2 번째 열 값만 가져오려면? 


In [ ]:
print(narray2[:, :2])
print(narray2[:, :2])

[[15 10]
 [17 19]
 [12 14]
 [18 18]]
[[15 10]
 [17 19]
 [12 14]
 [18 18]]




---



# (난이도 상) 조건 슬라이싱

논리연산자를 이용해서, 조건 슬라이싱이 가능하다.



In [ ]:
narray3=np.random.randn(4,4)
narray3

array([[-0.06491034, -0.96898025,  0.59124281, -0.7827755 ],
       [-0.44423283, -0.34518616, -0.88180055, -0.44265324],
       [-0.5409163 , -1.32322737, -0.11279892,  0.90734594],
       [ 0.81526991,  0.22909795, -1.02617878,  0.47752547]])

In [ ]:
narray3[narray3>0]
narray3[narray3<0]

array([-0.06491034, -0.96898025, -0.7827755 , -0.44423283, -0.34518616,
       -0.88180055, -0.44265324, -0.5409163 , -1.32322737, -0.11279892,
       -1.02617878])

In [ ]:
# 논리연산자를 사용해서 음수에 해당하는 값들은 전부다 0으로 초기화 세팅
# 이럴경우 원본이 함께 바뀌는 것을 명심!! ndarray 니까..
narray3[narray3<0] = 0
narray3

array([[0.        , 0.        , 0.59124281, 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.90734594],
       [0.81526991, 0.22909795, 0.        , 0.47752547]])

## 삼항 연산자

논리연산자와 같이 where 함수도 있음 :: 삼항 연산자


In [ ]:
narray3_1 = np.where(narray3>0, narray3, -1)
narray3_1

array([[-1.        , -1.        ,  0.59124281, -1.        ],
       [-1.        , -1.        , -1.        , -1.        ],
       [-1.        , -1.        , -1.        ,  0.90734594],
       [ 0.81526991,  0.22909795, -1.        ,  0.47752547]])

In [ ]:
# 중요!!
a = np.array([[1,2],[3,4],[5,6]])
a
bool_idx=(a>2)
print(bool_idx)
print(a[bool_idx])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]




---



# 통계함수

In [ ]:
narray2

array([[15, 10, 13, 13],
       [17, 19, 13, 15],
       [12, 14, 17, 16],
       [18, 18, 11, 16]])

In [ ]:
print(np.sum(narray2))
print(np.sum(narray2, axis=0)) # 0 은 모든 행을 더한 것
print(np.sum(narray2, axis=1)) # 1 은 모든 열을 더한 것

237
[62 61 54 60]
[51 64 59 63]


In [ ]:
np.cumsum(narray2, axis=0) # 누적된 합을 계속 더함 

array([[15, 10, 13, 13],
       [32, 29, 26, 28],
       [44, 43, 43, 44],
       [62, 61, 54, 60]])

In [ ]:
np.argmax(narray2, axis=0) # 정말 중요함니다요
# 모든 행들을 다 검색... 그 중에서 가장 큰 값의 인덱스를 리턴

array([3, 1, 2, 2])