In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive




---



# Numpy 배열 생성하기



1) array()사용하기

2) random() 사용하기

In [ ]:
import numpy as np

중요한 것은 Numpy 배열과 리스트를 비교하고, numpy를 이해 하는 것이 중요하다. (메모리적 측면)

numpy와 list의 가장 큰 차이점은 ?!
- 리스트는 출력결과 값들이 []안에 각 요소들이 ,(콤마)로 구분된다.


- numpy배열은 []안에 값들이 튜플형태로 나옴(콤마 없이)
- numpy 배열은 대괄호 안에 값들이 그냥 나열되어져 있다.

ndarray 타입 = N 차원의 배열이라는 뜻으로
ndarray클래스는 다차원행렬구조를 지원하는 Numpy의 핵심 클래스

In [ ]:
# 1) array() 함수 이용해서 생성
myList=[4,5,6,7] # 리스트
print(myList)
print(type(myList))
myArr = np.array(myList) # 넘파이 배열
print(type(myArr))

[4, 5, 6, 7]
<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
# 여기까지 리스트와 ndarray의 차이는 없다! 
mL_sub= myList[1:3]
print(mL_sub)

mA_sub= myArr[1:3]
print(mA_sub)

mL_sub[0] = -5
print(mL_sub)

mA_sub[0] = -5
print(mA_sub)

[5, 6]
[5 6]
[-5, 6]
[-5  6]


In [ ]:
# 근데 여기서부터 차이가 생긴다!!!
print(myList)
print(myArr)

[4, 5, 6, 7]
[ 4 -5  6  7]


<정리>


List는 원본이 바뀌지 않고 카피해서 새로운 걸 만든다. 

반면에, Numpy(=ndarray)는 원본 뷰가 함께 바뀐다.

리스트, np배열은 메모리 할당 부분에서 차이가 발생한다.

정리하자면, np 배열이 더 효율적이다. 즉 대용량의 데이터 할당에 유리하고, 속도적, 성능적 측면에서 더 좋다.



---



# 랜덤함수 사용하기 :: rand(), randint()

In [ ]:
# 랜덤함수는 0~1 사이의 실수 값이 나온다.
a = np.random.rand(5)
print(a)
print(type(a))

# b = np.random.randint? :: 함수 정의를 알아볼 때 사용
b = np.random.randint(1, 10, 5) # 중복가능, 1~9까지의 정수 랜덤 ndarray
print(b)
print(type(b))


c = np.random.randn(10) # 가우시안 표준분포 값을 뽑아낼 때 사용
print(c)
print(type(c))

[0.92473714 0.92198735 0.5205198  0.91636099 0.98726446]
<class 'numpy.ndarray'>
[7 7 3 3 3]
<class 'numpy.ndarray'>
[ 1.66341932 -0.31479724 -0.62250223  2.20839447 -0.0252811   2.07205108
 -0.30696916 -0.0628945   1.05445901 -0.87933661]
<class 'numpy.ndarray'>


<정리> 
ndarray 만드는 가장 쉬운 방법은
array()함수를 사용하거나, rand() 함수를 사용하면 된다.



---



# Numpy 초기화

3-9)


zeros(), ones(), arange() 함수를 이용해서 배열 생성과 동시에 특정한 값으로 초기화 한다.

이는 연산이 가능한데, 다시 말하자면 특정값으로 초기화를 할 수 있음을 의미한다.

In [ ]:
# 1. 0으로 채워진 ndarray가 하나 만들어짐(실수)
az = np.zeros(10)
print(az)

# 2. 1값으로 채워진 nd배열을 생성(실수)
ao = np.ones(10)
print(ao)

#3. 2값으로 채워진 nd배열을 생성(실수)
at = np.ones(10)+1
print(at)

#4.3 by 3 단위의 배열 생성(2차원 항등배열(?))
ae = np.eye(3)
print(ae)

ae1 = np.eye(5)
print(ae1)

#5. arange()
print(np.arange(3))
print(np.arange(3,7))
print(np.arange(3,7,2))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[0 1 2]
[3 4 5 6]
[3 5]


1차원과 2차원을 구분할 줄 알아야 한다.

대괄호 한개 (1차원) vector 구조라고 하며

대괄호 두개 (2차원) 구조를 pandas 구조라고 한다.



---



# 눈에 보이는 List와 Numpy 배열의 차이점

<정리>
리스트는 서로다른 자료구조를 가지는 원소 가능
반면에 np배열은 하나의 자료형만 저장이 가능하다.

In [ ]:
L = [1,2,3,'4',5,6]
print(L)

nArr = np.array(L)
print(nArr)

# nArr2 = np.array([11,22,33], dtype='float') :: 아래와 같은 표현
nArr2 = np.array([11,22,33], dtype=np.float64)
print(nArr2)

[1, 2, 3, '4', 5, 6]
['1' '2' '3' '4' '5' '6']
[11. 22. 33.]


<리스트와 넘파이배열의 차이점을 정리하자면>

1. 메모리 효율성

2. 같은 자리만 가지는 것이 차이점임 (메모리 효율과 관련)